// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ArrayStats = require("./ArrayStats.bs.js");

var array = /* float array */[
  1.2,
  2.3,
  3.4,
  4.5
];

var result = ArrayStats.max(array);

var max_result_001 = +(result === 4.5);

var max_result = /* tuple */[
  "ArrayStats.max",
  max_result_001,
  4.5,
  result
];

var array$1 = /* float array */[
  1.2,
  2.3,
  3.4,
  4.5
];

var result$1 = ArrayStats.min(array$1);

var min_result_001 = +(result$1 === 1.2);

var min_result = /* tuple */[
  "ArrayStats.min",
  min_result_001,
  1.2,
  result$1
];

var array$2 = /* float array */[
  1.2,
  2.3,
  3.4,
  4.5
];

var result$2 = ArrayStats.product(array$2);

var product_result_001 = +(result$2 === 42.227999999999994);

var product_result = /* tuple */[
  "ArrayStats.product",
  product_result_001,
  42.227999999999994,
  result$2
];

var array$3 = /* float array */[
  1.2,
  2.3,
  3.4,
  4.5
];

var result$3 = ArrayStats.sum_simple(array$3);

var sum_simple_result_001 = +(result$3 === 11.4);

var sum_simple_result = /* tuple */[
  "ArrayStats.sum_simple",
  sum_simple_result_001,
  11.4,
  result$3
];

var array$4 = /* float array */[
  1.2,
  2.3,
  3.4,
  4.5
];

var result$4 = ArrayStats.mean(array$4);

var mean_result1_001 = +(result$4 === 2.85);

var mean_result1 = /* tuple */[
  "ArrayStats.mean",
  mean_result1_001,
  2.85,
  result$4
];

var array$5 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$5 = ArrayStats.quantile_sorted(0, array$5);

var quantile_sorted_result1_001 = +(result$5 === 0);

var quantile_sorted_result1 = /* tuple */[
  "ArrayStats.quantile_sorted (0.)",
  quantile_sorted_result1_001,
  0,
  result$5
];

var array$6 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$6 = ArrayStats.quantile_sorted(0.25, array$6);

var quantile_sorted_result2_001 = +(result$6 === 1);

var quantile_sorted_result2 = /* tuple */[
  "ArrayStats.quantile_sorted (0.25)",
  quantile_sorted_result2_001,
  1,
  result$6
];

var array$7 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$7 = ArrayStats.quantile_sorted(0.5, array$7);

var quantile_sorted_result3_001 = +(result$7 === 2);

var quantile_sorted_result3 = /* tuple */[
  "ArrayStats.quantile_sorted (0.5)",
  quantile_sorted_result3_001,
  2,
  result$7
];

var array$8 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$8 = ArrayStats.quantile_sorted(0.75, array$8);

var quantile_sorted_result4_001 = +(result$8 === 3);

var quantile_sorted_result4 = /* tuple */[
  "ArrayStats.quantile_sorted (0.75)",
  quantile_sorted_result4_001,
  3,
  result$8
];

var array$9 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$9 = ArrayStats.quantile_sorted(1, array$9);

var quantile_sorted_result5_001 = +(result$9 === 4);

var quantile_sorted_result5 = /* tuple */[
  "ArrayStats.quantile_sorted (1.)",
  quantile_sorted_result5_001,
  4,
  result$9
];

var array$10 = /* float array */[
  3,
  0,
  1,
  2,
  4
];

var result$10 = ArrayStats.quantile(0.75, array$10);

var quantile_result_001 = +(result$10 === 3);

var quantile_result = /* tuple */[
  "ArrayStats.quantile",
  quantile_result_001,
  3,
  result$10
];

var array$11 = /* float array */[
  0,
  1,
  2,
  4
];

var result$11 = ArrayStats.interquartile_range(array$11);

var interquartile_range_result_001 = +(result$11 === 2);

var interquartile_range_result = /* tuple */[
  "ArrayStats.interquartile_range",
  interquartile_range_result_001,
  2,
  result$11
];

var array$12 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$12 = ArrayStats.median(array$12);

var median_result_001 = +(result$12 === 2);

var median_result = /* tuple */[
  "ArrayStats.median",
  median_result_001,
  2,
  result$12
];

var array$13 = /* float array */[
  -1,
  1,
  -1,
  1
];

var result$13 = ArrayStats.root_mean_square(array$13);

var root_mean_square_result_001 = +(result$13 === 1);

var root_mean_square_result = /* tuple */[
  "ArrayStats.root_mean_square",
  root_mean_square_result_001,
  1,
  result$13
];

var array$14 = /* float array */[
  0,
  1,
  2,
  3,
  4
];

var result$14 = ArrayStats.min_sorted(array$14);

var min_sorted_result_001 = +(result$14 === 0);

var min_sorted_result = /* tuple */[
  "ArrayStats.min_sorted",
  min_sorted_result_001,
  0,
  result$14
];

var array$15 = /* float array */[
  1,
  2,
  3,
  4,
  5,
  6
];

var result$15 = ArrayStats.variance(array$15);

var variance_result_001 = +(result$15 === 2.9166666666666665);

var variance_result = /* tuple */[
  "ArrayStats.variance",
  variance_result_001,
  2.9166666666666665,
  result$15
];

exports.max_result                 = max_result;
exports.min_result                 = min_result;
exports.product_result             = product_result;
exports.sum_simple_result          = sum_simple_result;
exports.mean_result1               = mean_result1;
exports.quantile_sorted_result1    = quantile_sorted_result1;
exports.quantile_sorted_result2    = quantile_sorted_result2;
exports.quantile_sorted_result3    = quantile_sorted_result3;
exports.quantile_sorted_result4    = quantile_sorted_result4;
exports.quantile_sorted_result5    = quantile_sorted_result5;
exports.quantile_result            = quantile_result;
exports.interquartile_range_result = interquartile_range_result;
exports.median_result              = median_result;
exports.root_mean_square_result    = root_mean_square_result;
exports.min_sorted_result          = min_sorted_result;
exports.variance_result            = variance_result;
/* result Not a pure module */
