// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ListStats = require("./ListStats.bs.js");

var result = ListStats.max(/* :: */[
      1.2,
      /* :: */[
        2.3,
        /* :: */[
          3.4,
          /* :: */[
            4.5,
            /* [] */0
          ]
        ]
      ]
    ]);

var max_result_001 = +(result === 4.5);

var max_result = /* tuple */[
  "ListStats.max",
  max_result_001,
  4.5,
  result
];

var result$1 = ListStats.min(/* :: */[
      1.2,
      /* :: */[
        2.3,
        /* :: */[
          3.4,
          /* :: */[
            4.5,
            /* [] */0
          ]
        ]
      ]
    ]);

var min_result_001 = +(result$1 === 1.2);

var min_result = /* tuple */[
  "ListStats.min",
  min_result_001,
  1.2,
  result$1
];

var result$2 = ListStats.product(/* :: */[
      1.2,
      /* :: */[
        2.3,
        /* :: */[
          3.4,
          /* :: */[
            4.5,
            /* [] */0
          ]
        ]
      ]
    ]);

var product_result_001 = +(result$2 === 42.227999999999994);

var product_result = /* tuple */[
  "ListStats.product",
  product_result_001,
  42.227999999999994,
  result$2
];

var result$3 = ListStats.sum_simple(/* :: */[
      1.2,
      /* :: */[
        2.3,
        /* :: */[
          3.4,
          /* :: */[
            4.5,
            /* [] */0
          ]
        ]
      ]
    ]);

var sum_simple_result_001 = +(result$3 === 11.4);

var sum_simple_result = /* tuple */[
  "ListStats.sum_simple",
  sum_simple_result_001,
  11.4,
  result$3
];

var result$4 = ListStats.mean(/* :: */[
      1.2,
      /* :: */[
        2.3,
        /* :: */[
          3.4,
          /* :: */[
            4.5,
            /* [] */0
          ]
        ]
      ]
    ]);

var mean_result1_001 = +(result$4 === 2.85);

var mean_result1 = /* tuple */[
  "ListStats.mean",
  mean_result1_001,
  2.85,
  result$4
];

var result$5 = ListStats.quantile_sorted(0, /* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_sorted_result1_001 = +(result$5 === 0);

var quantile_sorted_result1 = /* tuple */[
  "ListStats.quantile_sorted (0.)",
  quantile_sorted_result1_001,
  0,
  result$5
];

var result$6 = ListStats.quantile_sorted(0.25, /* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_sorted_result2_001 = +(result$6 === 1);

var quantile_sorted_result2 = /* tuple */[
  "ListStats.quantile_sorted (0.25)",
  quantile_sorted_result2_001,
  1,
  result$6
];

var result$7 = ListStats.quantile_sorted(0.5, /* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_sorted_result3_001 = +(result$7 === 2);

var quantile_sorted_result3 = /* tuple */[
  "ListStats.quantile_sorted (0.5)",
  quantile_sorted_result3_001,
  2,
  result$7
];

var result$8 = ListStats.quantile_sorted(0.75, /* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_sorted_result4_001 = +(result$8 === 3);

var quantile_sorted_result4 = /* tuple */[
  "ListStats.quantile_sorted (0.75)",
  quantile_sorted_result4_001,
  3,
  result$8
];

var result$9 = ListStats.quantile_sorted(1, /* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_sorted_result5_001 = +(result$9 === 4);

var quantile_sorted_result5 = /* tuple */[
  "ListStats.quantile_sorted (1.)",
  quantile_sorted_result5_001,
  4,
  result$9
];

var result$10 = ListStats.quantile(0.75, /* :: */[
      3,
      /* :: */[
        0,
        /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quantile_result_001 = +(result$10 === 3);

var quantile_result = /* tuple */[
  "ListStats.quantile",
  quantile_result_001,
  3,
  result$10
];

var result$11 = ListStats.median(/* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var median_result_001 = +(result$11 === 2);

var median_result = /* tuple */[
  "ListStats.median",
  median_result_001,
  2,
  result$11
];

var result$12 = ListStats.root_mean_square(/* :: */[
      -1,
      /* :: */[
        1,
        /* :: */[
          -1,
          /* :: */[
            1,
            /* [] */0
          ]
        ]
      ]
    ]);

var root_mean_square_result_001 = +(result$12 === 1);

var root_mean_square_result = /* tuple */[
  "ListStats.root_mean_square",
  root_mean_square_result_001,
  1,
  result$12
];

var result$13 = ListStats.min_sorted(/* :: */[
      0,
      /* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              4,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var min_sorted_result_001 = +(result$13 === 0);

var min_sorted_result = /* tuple */[
  "ListStats.min_sorted",
  min_sorted_result_001,
  0,
  result$13
];

var result$14 = ListStats.variance(/* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* :: */[
            4,
            /* :: */[
              5,
              /* :: */[
                6,
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var variance_result_001 = +(result$14 === 2.9166666666666665);

var variance_result = /* tuple */[
  "ListStats.min_sorted",
  variance_result_001,
  2.9166666666666665,
  result$14
];

exports.max_result              = max_result;
exports.min_result              = min_result;
exports.product_result          = product_result;
exports.sum_simple_result       = sum_simple_result;
exports.mean_result1            = mean_result1;
exports.quantile_sorted_result1 = quantile_sorted_result1;
exports.quantile_sorted_result2 = quantile_sorted_result2;
exports.quantile_sorted_result3 = quantile_sorted_result3;
exports.quantile_sorted_result4 = quantile_sorted_result4;
exports.quantile_sorted_result5 = quantile_sorted_result5;
exports.quantile_result         = quantile_result;
exports.median_result           = median_result;
exports.root_mean_square_result = root_mean_square_result;
exports.min_sorted_result       = min_sorted_result;
exports.variance_result         = variance_result;
/* result Not a pure module */
