// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function add_to_mean(mean, listLength, newValue) {
  return mean + (newValue - mean) / (listLength + 1);
}

function factorial(x) {
  if (x <= 1) {
    return x;
  } else {
    return Caml_int32.imul(x, factorial(x - 1 | 0));
  }
}

var Utils = /* module */[/* factorial */factorial];

exports.add_to_mean = add_to_mean;
exports.Utils       = Utils;
/* No side effect */
