// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Stats = require("./Stats.bs.js");

var result = Stats.Utils[/* add_to_mean */0](14, 5, 53);

var add_to_mean_result_001 = +(result === 20.5);

var add_to_mean_result = /* tuple */[
  "Stats.add_to_mean",
  add_to_mean_result_001,
  20.5,
  result
];

var result$1 = Stats.Utils[/* factorial */1](13);

var factorial_result_001 = +(result$1 === 1932053504);

var factorial_result = /* tuple */[
  "Stats.Utils.factorial",
  factorial_result_001,
  1932053504,
  result$1
];

exports.add_to_mean_result = add_to_mean_result;
exports.factorial_result   = factorial_result;
/* result Not a pure module */
