// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Stats = require("./Stats.bs.js");

var result = Stats.add_to_mean(14, 5, 53);

var add_to_mean_result_001 = +(result === 20.5);

var add_to_mean_result = /* tuple */[
  "Stats.add_to_mean",
  add_to_mean_result_001,
  20.5,
  result
];

exports.add_to_mean_result = add_to_mean_result;
/* result Not a pure module */
